JakeWharton/RxBinding

rxandroid/src/main/java/rx/android/plugins/RxAndroidLogHook.java, rxandroid/src/main/java/rx/android/plugins/RxAndroidPlugins.java, rxandroid/src/main/java/rx/android/util/RxLog.java
This allows one to extend the logging system, e.g. if you're using
Timber you can continue to do so even with this library.
=> Added RxAndroidLogHook, use in RxLog

rxandroid/src/androidTest/java/rx/android/widget/RxCompoundButtonTest.java
Remove copy/pasta tests from original creation of this test class.
=> Add CompoundBuddon tests for toggle, checked.

rxandroid/src/androidTest/java/rx/android/view/RxViewTest.java, rxandroid/src/androidTest/java/rx/android/widget/RxCompoundButtonTest.java, rxandroid/src/androidTest/java/rx/android/widget/RxTextViewTest.java, rxandroid/src/main/java/rx/android/internal/Functions.java, rxandroid/src/main/java/rx/android/plugins/RxAndroidPlugins.java, rxandroid/src/main/java/rx/android/util/RxLog.java, rxandroid/src/main/java/rx/android/view/RxView.java, rxandroid/src/main/java/rx/android/view/ViewClickEvent.java, rxandroid/src/main/java/rx/android/view/ViewClickEventOnSubscribe.java, rxandroid/src/main/java/rx/android/view/ViewClickOnSubscribe.java, rxandroid/src/main/java/rx/android/view/ViewDragEvent.java, rxandroid/src/main/java/rx/android/view/ViewDragEventOnSubscribe.java, rxandroid/src/main/java/rx/android/view/ViewEvent.java, rxandroid/src/main/java/rx/android/view/ViewFocusChangeEvent.java, rxandroid/src/main/java/rx/android/view/ViewFocusChangeEventOnSubscribe.java, rxandroid/src/main/java/rx/android/view/ViewLongClickEvent.java, rxandroid/src/main/java/rx/android/view/ViewLongClickEventOnSubscribe.java, rxandroid/src/main/java/rx/android/view/ViewLongClickOnSubscribe.java, rxandroid/src/main/java/rx/android/widget/AdapterViewItemSelectionEvent.java, rxandroid/src/main/java/rx/android/widget/AdapterViewItemSelectionOnSubscribe.java, rxandroid/src/main/java/rx/android/widget/AdapterViewNothingSelectionEvent.java, rxandroid/src/main/java/rx/android/widget/AdapterViewSelectionEvent.java, rxandroid/src/main/java/rx/android/widget/AdapterViewSelectionOnSubscribe.java, rxandroid/src/main/java/rx/android/widget/CompoundButtonCheckedChangeEvent.java, rxandroid/src/main/java/rx/android/widget/CompoundButtonCheckedChangeEventOnSubscribe.java, rxandroid/src/main/java/rx/android/widget/RxAdapterView.java, rxandroid/src/main/java/rx/android/widget/TextViewTextChangeEvent.java, rxandroid/src/main/java/rx/android/widget/TextViewTextEventOnSubscribe.java
* Remove clock and timestamp things. Use timestamp() instead.
* Add AdapterView methods.
* equals/hashCode/toString for events.
=> Import from internal.

rxandroid-kotlin/src/main/kotlin/rx/android/view/RxView.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxAdapterView.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxCompoundButton.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxProgressBar.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxRadioGroup.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxSeekBar.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxTextView.kt
The power of `sed` to the rescue! Refs #19.
=> Correct extension methods to use implicit 'this' reference.

rxandroid-kotlin/src/main/kotlin/rx/android/view/RxView.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxAdapterView.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxCompoundButton.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxProgressBar.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxRadioGroup.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxSeekBar.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxTextView.kt
=> Make extension methods public, opt in to inlining.

README.md, rxandroid-kotlin/src/main/kotlin/rx/android/view/RxView.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxAdapterView.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxCompoundButton.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxProgressBar.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxRadioGroup.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxRatingBar.kt, rxandroid-kotlin/src/main/kotlin/rx/android/widget/RxTextView.kt, rxandroid/src/androidTest/java/rx/android/view/RxViewTest.java, rxandroid/src/androidTest/java/rx/android/widget/RxAdapterViewTest.java, rxandroid/src/androidTest/java/rx/android/widget/RxCompoundButtonTest.java, rxandroid/src/androidTest/java/rx/android/widget/RxProgressBarTest.java, rxandroid/src/androidTest/java/rx/android/widget/RxRadioGroupTest.java, rxandroid/src/androidTest/java/rx/android/widget/RxRatingBarTest.java, rxandroid/src/androidTest/java/rx/android/widget/RxTextViewTest.java, rxandroid/src/main/java/rx/android/view/RxView.java, rxandroid/src/main/java/rx/android/widget/RxAdapterView.java, rxandroid/src/main/java/rx/android/widget/RxCompoundButton.java, rxandroid/src/main/java/rx/android/widget/RxProgressBar.java, rxandroid/src/main/java/rx/android/widget/RxRadioGroup.java, rxandroid/src/main/java/rx/android/widget/RxRatingBar.java, rxandroid/src/main/java/rx/android/widget/RxTextView.java
=> Remove 'set' prefix on action factories.

build.gradle
Changelog: https://github.com/ReactiveX/RxJava/releases/tag/v1.0.12
=> RxJava 1.0.12

gradle/gradle-mvn-push.gradle, rxbinding-kotlin/build.gradle, rxbinding-support-v4-kotlin/build.gradle
=> Enable publish from Kotlin modules.

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/view/RxView.kt, rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxView.java
=> Remove needless link to well-known View constants.

rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding/support/v4/widget/RxDrawerLayout.java, rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayout.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxView.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxAdapter.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxAdapterView.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxCompoundButton.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxProgressBar.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxRadioGroup.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxRatingBar.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxSeekBar.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxTextView.java
It is a programmer error to call these and ignore their return type.
(With apologies to @hzsweers... hope this doesn't break anything!)
=> Add @CheckResult to all factory methods.

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxTextSwitcher.kt, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxTextSwitcherTest.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxTextSwitcher.java
=> Add TextSwitcher bindings.

build.gradle, rxbinding-design-kotlin/build.gradle, rxbinding-design-kotlin/gradle.properties, rxbinding-design-kotlin/src/main/AndroidManifest.xml, rxbinding-design-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/design/widget/RxTabLayout.kt, rxbinding-design/build.gradle, rxbinding-design/gradle.properties, rxbinding-design/src/androidTest/java/com/jakewharton/rxbinding/support/design/widget/RxTabLayoutTest.java, rxbinding-design/src/main/AndroidManifest.xml, rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/RxTabLayout.java, rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/TabLayoutSelectionEvent.java, rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/TabLayoutSelectionEventOnSubscribe.java, rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/TabLayoutSelectionsOnSubscribe.java, settings.gradle
=> Start design lib module with TabLayout bindings.

rxbinding-design-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/design/widget/RxNavigationView.kt, rxbinding-design/src/androidTest/java/com/jakewharton/rxbinding/support/design/widget/RxNavigationViewTest.java, rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/NavigationViewItemSelectionsOnSubscribe.java, rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/RxNavigationView.java
=> Add binding for navigation view item selections.

build.gradle, rxbinding-appcompat-v7-kotlin/build.gradle, rxbinding-appcompat-v7-kotlin/gradle.properties, rxbinding-appcompat-v7-kotlin/src/main/AndroidManifest.xml, rxbinding-appcompat-v7-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v7/widget/RxToolbar.kt, rxbinding-appcompat-v7/build.gradle, rxbinding-appcompat-v7/gradle.properties, rxbinding-appcompat-v7/src/androidTest/java/com/jakewharton/rxbinding/support/v7/widget/RxToolbarTest.java, rxbinding-appcompat-v7/src/main/AndroidManifest.xml, rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/RxToolbar.java, rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/ToolbarItemClickOnSubscribe.java, settings.gradle
=> Start the AppCompat module with Toolbar item click binding.

rxbinding-design-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/design/widget/RxSnackbar.kt, rxbinding-design/src/androidTest/java/com/jakewharton/rxbinding/support/design/widget/RxSnackbarTest.java, rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/RxSnackbar.java, rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/SnackbarDismissesOnSubscribe.java
=> Snackbar dismiss binding.

rxbinding-appcompat-v7-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v7/widget/RxSearchView.kt, rxbinding-appcompat-v7/src/androidTest/java/com/jakewharton/rxbinding/support/v7/widget/RxSearchViewTest.java, rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/RxSearchView.java, rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/SearchViewQueryTextChangeEventsOnSubscribe.java, rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/SearchViewQueryTextChangesOnSubscribe.java, rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/SearchViewQueryTextEvent.java, rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxSearchView.kt, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxSearchViewTest.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxSearchView.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/SearchViewQueryTextChangeEventsOnSubscribe.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/SearchViewQueryTextChangesOnSubscribe.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/SearchViewQueryTextEvent.java
=> SearchView Bindings

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/view/RxView.kt, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/view/RxViewTest.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxView.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewHoverEvent.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewHoverEventOnSubscribe.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewHoverOnSubscribe.java, testing-utils/src/main/java/com/jakewharton/rxbinding/MotionEventUtil.java
Added bindings for hover events registered by `View.OnHoverListener()`.
=> Added hover event bindings.

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/view/RxView.kt, rxbinding-recyclerview-v7-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v7/widget/RxRecyclerViewAdapter.kt, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/view/RxViewTest.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxView.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewLayoutChangeEvent.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewLayoutChangeEventOnSubscribe.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewLayoutChangeOnSubscribe.java
Added bindings for layout changes registered by `View.OnLayoutChangeListener`.
=> Added layout change bindings.

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/view/RxView.kt, rxbinding/src/androidTest/AndroidManifest.xml, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/view/RxViewSystemUiVisibilityTest.java, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/view/RxViewSystemUiVisibilityTestActivity.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxView.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewSystemUiVisibilityChangeEvent.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewSystemUiVisibilityChangeEventOnSubscribe.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewSystemUiVisibilityChangeOnSubscribe.java
Bindings for `View.OnSystemUiVisibilityChangeListener`.
=> Added bindings for system UI visibility changes.

rxbinding-appcompat-v7-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v7/widget/RxToolbar.kt, rxbinding-appcompat-v7/src/androidTest/AndroidManifest.xml, rxbinding-appcompat-v7/src/androidTest/java/com/jakewharton/rxbinding/support/v7/widget/RxToolbarTest.java, rxbinding-appcompat-v7/src/androidTest/java/com/jakewharton/rxbinding/support/v7/widget/RxToolbarTestActivity.java, rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/RxToolbar.java, rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/ToolbarNavigationClickOnSubscribe.java, rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxToolbar.kt, rxbinding/src/androidTest/AndroidManifest.xml, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxToolbarTest.java, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxToolbarTestActivity.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxToolbar.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/ToolbarNavigationClickOnSubscribe.java
=> add toolbar navigation click bindings

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxTextView.kt, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxTextViewTest.java, rxbinding/src/androidTest/res/values/strings.xml, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxTextView.java
=> Add error & errorRes actions to RxTextView

build.gradle, gradle.properties
Can't wait when this library supports M13 :)
=> Updated Kotlin version to M13

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/view/RxView.kt, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/view/RxViewTest.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxView.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewTreeObserverPreDrawOnSubscribe.java
=> Add ViewTreeObserver PreDraw event binding

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/view/RxView.kt, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/view/RxViewTest.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxView.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewTreeObserverGlobalLayoutOnSubscribe.java
=> Add ViewTreeObserver GlobalLayout event binding

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/view/RxView.kt, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/view/RxViewTest.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxView.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewTreeObserverDrawOnSubscribe.java
=> Add ViewTreeObserver draw event binding

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/view/RxMenuItem.kt, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/view/RxMenuItemTest.java, rxbinding/src/androidTest/res/drawable/icon.xml, rxbinding/src/main/java/com/jakewharton/rxbinding/view/MenuItemActionViewEvent.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/MenuItemActionViewEventOnSubscribe.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/MenuItemClickOnSubscribe.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/MenuItemEvent.java, rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxMenuItem.java
Since `MenuItem` is an interface I didn't want to add *everything* in it (since some of it is just setup code), but I added what I thought was reasonable.
=> Created RxMenuItem

build.gradle
Fixes https://github.com/JakeWharton/RxBinding/issues/157
=> Update Kotlin version to M14

build.gradle
=> Upgrade Kotlin to 1.0 beta.

gradle/gradle-mvn-push.gradle
=> Exclude internal package from Javadoc.

gradle/wrapper/gradle-wrapper.properties
Drop the checksum, I don't want to update that every time.
=> Gradle 2.8

rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayoutTest.java
=> Mark STR test as flaky to hopefully prevent some CI failures for now.

rxbinding-support-v4-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v4/view/RxMenuItemCompat.kt, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/view/RxMenuItemCompatTest.java, rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding/support/v4/view/MenuItemActionViewEventOnSubscribe.java, rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding/support/v4/view/RxMenuItemCompat.java
=> Add RxMenuItemCompat actionViewEvents observable

dependencies.gradle
Updates to the newly released 1.0.0
=> Kotlin 1.0.0

rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxView.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxTextView.java
=> Document items which are mutable and not safe to delay usage of.

rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewEditorActionEvent.java
=> KeyEvent is nullable in TextViewEditorActionEvent

.travis.yml, dependencies.gradle, gradle/wrapper/gradle-wrapper.properties, rxbinding-appcompat-v7/build.gradle, rxbinding-design/build.gradle, rxbinding-design/src/androidTest/java/com/jakewharton/rxbinding/support/design/widget/RxSwipeDismissBehaviorTest.java, rxbinding-design/src/androidTest/java/com/jakewharton/rxbinding/support/design/widget/RxSwipeDismissBehaviorTestActivity.java, rxbinding-design/src/androidTest/java/com/jakewharton/rxbinding/support/design/widget/RxTextInputLayoutTest.java, rxbinding-leanback-v17/build.gradle, rxbinding-recyclerview-v7/build.gradle, rxbinding-support-v4/build.gradle, rxbinding/build.gradle, testing-utils/build.gradle
=> Update API and friends to 24.

buildSrc/src/main/kotlin/com/jakewharton/rxbinding/project/KotlinGenTask.kt, rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxView.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxToolbar.java
=> Switch TargetApi for more correct RequiresApi annotation.

dependencies.gradle, rxbinding-design-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/design/widget/RxBottomNavigationView.kt, rxbinding-design/src/androidTest/java/com/jakewharton/rxbinding/support/design/widget/RxBottomNavigationViewTest.java, rxbinding-design/src/androidTest/res/menu/menu.xml, rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/BottomNavigationViewItemSelectionsOnSubscribe.java, rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/RxBottomNavigationView.java
=> Add BottomNavigationView binding

rxbinding-appcompat-v7-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v7/widget/RxToolbar.kt, rxbinding-appcompat-v7/src/androidTest/java/com/jakewharton/rxbinding/support/v7/widget/RxToolbarTest.java, rxbinding-appcompat-v7/src/androidTest/res/values/strings.xml, rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/RxToolbar.java, rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxToolbar.kt, rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxToolbarTest.java, rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxToolbar.java
=> Added Toolbar title and subtitle methods

buildSrc/README.md, buildSrc/build.gradle, buildSrc/src/main/kotlin/com/jakewharton/rxbinding/project/ValidateBindingsTask.kt
=> Removed RxJava from Gradle plugin, using Kotlin stdlib instead

rxbinding/src/main/java/com/jakewharton/rxbinding2/view/RxMenuItem.java
instead of FUNC1_ALWAYS_TRUE from old package.
=> Use Functions.FUNCTION_ALWAYS_TRUE from correct package

rxbinding/src/androidTest/AndroidManifest.xml, rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxCompoundButtonTest.java, rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxTextViewTest.java, rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxToolbarTest.java, rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxToolbarTestActivity.java, rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/CompoundButtonCheckedChangeObservable.java, rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/TextViewAfterTextChangeEventObservable.java, rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/TextViewBeforeTextChangeEventObservable.java, rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/TextViewTextChangeEventObservable.java, rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/TextViewTextObservable.java
This PR ports tests for widgets currently merged with rxjava-two.
- RxCompoundButtonTest
- RxTextViewTest
- RxToolbarTest
=> Port part of tests from com.jakewharton.rxbinding.widget to RxJava2

rxbinding-support-v4/src/androidTest/AndroidManifest.xml, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/view/RxMenuItemCompatTest.java, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/view/RxViewPagerTest.java, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/view/RxViewPagerTestActivity.java, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxDrawerLayoutTest.java, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxDrawerLayoutTestActivity.java, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxNestedScrollViewTest.java, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxNestedScrollViewTestActivity.java, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxSlidingPaneLayoutTest.java, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxSlidingPaneLayoutTestActivity.java, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxSwipeRefreshLayoutTest.java, rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxSwipeRefreshLayoutTestActivity.java, rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding2/support/v4/widget/RxSwipeRefreshLayout.java, rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding2/support/v4/widget/SwipeRefreshLayoutRefreshObservable.java
Does not include new RecordingObserver -- saw that existed in a current pull request.
=> Port support v4 tests to RxJava 2

rxbinding-leanback-v17/src/main/java/com/jakewharton/rxbinding2/support/v17/leanback/widget/RxSearchEditText.java, rxbinding-leanback-v17/src/main/java/com/jakewharton/rxbinding2/support/v17/leanback/widget/SearchEditTextKeyboardDismissOnSubscribe.java, rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/PopupMenuDismissObservable.java, rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/RxPopupMenu.java
to not leak implementation details to library users.
=> Change Observable<Notification> to <Object>

rxbinding-leanback-v17/src/androidTest/java/com/jakewharton/rxbinding2/support/v17/leanback/widget/RxSearchBarTest.java, rxbinding-leanback-v17/src/androidTest/java/com/jakewharton/rxbinding2/support/v17/leanback/widget/RxSearchEditTextTest.java
This fixes tests moved in 512e404
=> Port com.jakewharton.rxbinding.support.v17 tests to RxJava 2

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/widget/RxTextView.kt, rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/RxTextView.java
=> Document from which property the initial after text change event comes.

rxbinding-appcompat-v7-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/support/v7/widget/RxSearchView.kt, rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding2/support/v7/widget/RxSearchView.java, rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/widget/RxSearchView.kt, rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/RxSearchView.java
I fixed minor typos.
Here are the typos in this repository.
https://github.com/JakeWharton/RxBinding/search?utf8=%E2%9C%93&q=weather&type=
=> Fix typos (weather -> whether)

rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/SeekBarChangeObservable.java
=> Clear OnSeekBarChangeListener at onDispose

rxbinding/build.gradle, rxbinding/src/main/proguard-consumer.pro
=> Add consumer ProGuard rules for AutoValue usage.

rxbinding-material/src/main/java/com/jakewharton/rxbinding3/material/TabLayoutSelectionsObservable.kt
=> TabLayoutSelection.Listener : BaseOnTabSelectedListener
