JakeWharton/RxBinding

rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewClickEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewClickOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewDragEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewDragOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewFocusChangeEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewFocusChangeOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewLongClickEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewLongClickOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewTouchEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewTouchOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/AdapterDataChangeOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/AdapterViewItemClickEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/AdapterViewItemClickOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/AdapterViewItemLongClickEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/AdapterViewItemLongClickOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/AdapterViewItemSelectionOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/AdapterViewSelectionOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/CompoundButtonCheckedChangeEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/CompoundButtonCheckedChangeOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RadioGroupCheckedChangeEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RadioGroupCheckedChangeOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RatingBarRatingChangeEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RatingBarRatingChangeOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/SeekBarChangeEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/SeekBarChangeOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewEditorActionEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewEditorActionOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewTextEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewTextOnSubscribe.java

This solves a subtle race due to the fact that we have to post to the main thread to remove the listener. In some cases events could be queued and processed after the downstream subscriber called unsubscribe but we had not detached the listener.

Check for subscription before calling through with data.

---

rxbinding/build.gradle
rxbinding/src/androidTest/AndroidManifest.xml
rxbinding/src/androidTest/java/com/jakewharton/rxbinding/RxBindingTestRunner.java

Addresses #27 
I guess the question is - is there any way to avoid copy-pasting the test runner into the other modules? AFAIK the `androidTest` source set is not available in the `rxbinding-support-v4` module for instance, so the same issue will show up?

Add custom test runner to kill keyguard and hold wake lock

---

.gitignore

IntelliJ will generate annotation information for its static analysis into a top-level `annotations` directory. This adds a line to .gitignore to ignore it

Ignore kotlin generated annotations directory

---

rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxAdapterView.java

Kotlin generation can't dig into AdapterView's implementation to see the requirements

Make type parameters explicit in RxAdapterView

---

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/view/RxView.kt
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxAdapter.kt
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxAdapterView.kt
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxCompoundButton.kt
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxProgressBar.kt
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxRadioGroup.kt
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxRatingBar.kt
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxSeekBar.kt
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxTextView.kt
rxbinding-support-v4-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v4/widget/RxDrawerLayout.kt

This includes some touchups to the documentations to make them more kotlin-esque and adds the following missing implementations:
- `View.drags(Func1)`
- `View.dragEvents(Func1)`
- `View.longClicks(Func0)`
- `View.longClickEvents(Func1)`
- `View.touches()`
- `View.touches(Func0)`
- `View.touchEvents()`
- `View.touchEvents(Func1)`
- `View.visibility()`
- `AdapterView.itemLongClicks(Func0)`
- `AdapterView.itemLongClickEvents(Func1)`
- `TextView.editorActions()`
- `TextView.editorActionEvents()`

Regenerate kotlin bindings via KotlinGen plugin

---

rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxRadioGroupTest.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxRadioGroup.java

Radio group tends to fire changes twice and re-fire already-selected IDs when clearing.

Debounce checked changes in radio groups.

---

buildSrc/src/main/groovy/com/jakewharton/rxbinding/project/KotlinGenTask.groovy
rxbinding/src/main/java/com/jakewharton/rxbinding/internal/MainThreadSubscription.java

Should properly handle nested method type parameters now and also handle "? extends ___" wildcard objects, which use the `out` specifier rather than `in`
/CC @chemouna, this should fix the Kotlin generation issues in #109

Variance annotation support and fixed typeParams

---

rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewEvent.java

Since `ViewEvent` doesn't contain a timestamp anymore.

Remove timestamp from ViewEvent docs.

---

rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxTextView.kt
rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxTextViewTest.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxTextView.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewAfterTextChangeEvent.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewAfterTextChangeEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewBeforeTextChangeEvent.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewBeforeTextChangeEventOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewTextChangeEventOnSubscribe.java

Add Before & After TextChangeEvent bindings to RxTextView

---

.travis.yml
build.gradle
rxbinding-leanback-v17-kotlin/build.gradle
rxbinding-leanback-v17-kotlin/gradle.properties
rxbinding-leanback-v17-kotlin/src/main/AndroidManifest.xml
rxbinding-leanback-v17-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v17/leanback/widget/RxSearchBar.kt
rxbinding-leanback-v17-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v17/leanback/widget/RxSearchEditText.kt
rxbinding-leanback-v17/build.gradle
rxbinding-leanback-v17/gradle.properties
rxbinding-leanback-v17/src/androidTest/AndroidManifest.xml
rxbinding-leanback-v17/src/androidTest/java/com/jakewharton/rxbinding/support/v17/leanback/widget/RxSearchBarTest.java
rxbinding-leanback-v17/src/androidTest/java/com/jakewharton/rxbinding/support/v17/leanback/widget/RxSearchBarTestActivity.java
rxbinding-leanback-v17/src/androidTest/java/com/jakewharton/rxbinding/support/v17/leanback/widget/RxSearchEditTextTest.java
rxbinding-leanback-v17/src/main/AndroidManifest.xml
rxbinding-leanback-v17/src/main/java/com/jakewharton/rxbinding/support/v17/leanback/widget/RxSearchBar.java
rxbinding-leanback-v17/src/main/java/com/jakewharton/rxbinding/support/v17/leanback/widget/RxSearchEditText.java
rxbinding-leanback-v17/src/main/java/com/jakewharton/rxbinding/support/v17/leanback/widget/SearchBarSearchQueryChangeEventsOnSubscribe.java
rxbinding-leanback-v17/src/main/java/com/jakewharton/rxbinding/support/v17/leanback/widget/SearchBarSearchQueryChangesOnSubscribe.java
rxbinding-leanback-v17/src/main/java/com/jakewharton/rxbinding/support/v17/leanback/widget/SearchBarSearchQueryEvent.java
rxbinding-leanback-v17/src/main/java/com/jakewharton/rxbinding/support/v17/leanback/widget/SearchEditTextKeyboardDismissOnSubscribe.java
settings.gradle

Addresses https://github.com/JakeWharton/RxBinding/issues/60
Also, fixes toString in SearchViewQueryTextEvent.

Add support v17 Leanback

---

buildSrc/src/main/groovy/com/jakewharton/rxbinding/project/KotlinGenTask.groovy
rxbinding-appcompat-v7-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v7/widget/RxToolbar.kt
rxbinding-appcompat-v7/src/androidTest/java/com/jakewharton/rxbinding/support/v7/widget/RxToolbarTest.java
rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/RxToolbar.java
rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/ToolbarNavigationClickOnSubscribe.java
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/view/RxMenuItem.kt
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/view/RxView.kt
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxToolbar.kt
rxbinding-leanback-v17-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v17/leanback/widget/RxSearchEditText.kt
rxbinding-support-v4-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayout.kt
rxbinding/src/androidTest/java/com/jakewharton/rxbinding/view/RxMenuItemTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding/view/RxViewAttachTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding/view/RxViewTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxToolbarTest.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/MenuItemClickOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxMenuItem.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/RxView.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewAttachesOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewClickOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewLayoutChangeOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewLongClickOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewTreeObserverDrawOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewTreeObserverGlobalLayoutOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewTreeObserverPreDrawOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxToolbar.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/ToolbarNavigationClickOnSubscribe.java

Use Void not Object for stateless events, Unit in Kotlin.

---

rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxAutoCompleteTextViewTest.java

I managed to get the failure on this test when testing on the mobile device (Nexus 5) in landscape mode. The keyboard would fully cover the screen and drop-down list was not visible.
If tests run well it's the same problem on Travis CI as well.
Fixes #183.
*EDIT: Guess that's not the problem, will look into it more.*
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jakewharton/rxbinding/189)

Fixes RxAutoCompleteTextViewTest.itemClickEvents() test.

---

rxbinding-appcompat-v7-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v7/widget/RxPopupMenu.kt
rxbinding-appcompat-v7/src/androidTest/AndroidManifest.xml
rxbinding-appcompat-v7/src/androidTest/java/com/jakewharton/rxbinding/support/v7/widget/RxPopupMenuTest.java
rxbinding-appcompat-v7/src/androidTest/java/com/jakewharton/rxbinding/support/v7/widget/RxPopupMenuTestActivity.java
rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/PopupMenuDismissOnSubscribe.java
rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/PopupMenuItemClickOnSubscribe.java
rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding/support/v7/widget/RxPopupMenu.java
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding/widget/RxPopupMenu.kt
rxbinding/src/androidTest/AndroidManifest.xml
rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxPopupMenuTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxPopupMenuTestActivity.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/PopupMenuDismissOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/PopupMenuItemClickOnSubscribe.java
rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxPopupMenu.java

Added bindings for the platform and Appcompat versions of PopupMenu. Closes #222. 
I wasn't sure if `show` and `dismiss` should have `Action1` bindings. I imagine have a single `Action1<? super Boolean>` binding to both show and dismiss is preferable?

Add RxPopupMenu

---

rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayoutTest.java
rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayoutTestActivity.java
rxbinding-support-v4/src/androidTest/res/values/ids.xml
rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding/support/v4/widget/SwipeRefreshLayoutRefreshOnSubscribe.java

After examining `RxSwipeRefreshLayoutTest`, it seems that the automatically ran `.setRefresh(false)` (which performs stopping the refresh animation) could happen to be called between the swipe release and the actual loading/refreshing animation, causing the animation to stop and listener never to be called, thus not recorded.
So the solution I did was to post refresh stop 2 seconds after the first touch on a view happens (which is enough time for the swipe - 1500ms and the recorder to catch up the listener). This should avoid flakyness in this test.
Fixes #72.

Fixed RxSwipeRefreshLayoutTest test

---

rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/TabLayoutSelectionEvent.java

Minor typo fix in TabLayoutSelectionEvent#toString()

Fix typo in TabLayoutSelectionEvent.toString()

---

rxbinding-support-v4-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/v4/widget/RxSlidingPaneLayout.kt
rxbinding-support-v4/src/androidTest/AndroidManifest.xml
rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSlidingPaneLayoutTest.java
rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSlidingPaneLayoutTestActivity.java
rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding/support/v4/widget/RxSlidingPaneLayout.java
rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding/support/v4/widget/SlidingPaneLayoutPaneOpenedOnSubscribe.java
rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding/support/v4/widget/SlidingPaneLayoutSlideOnSubscribe.java

refs #270 
First pass of new bindings for SlidingPaneLayout:
- _RxSlidingPaneLayout.paneOpen(view)_: boolean emissions for open state
- _RxSlidingPaneLayout.slides(view)_: float emissions for slide offset
- _RxSlidingPaneLayout.open()_: boolean Action to open or close
Looking for comments especially on the tests since this is my first submission to the project.

add new SlidingPaneLayout bindings

---

rxbinding-design/src/androidTest/java/com/jakewharton/rxbinding/support/design/widget/RxSwipeDismissBehaviorTest.java

Looks like changing the swipe speed on the test from SLOW to FAST fixes the flakiness. SLOW swipe wasn't triggering the actual dismissal.
Closes #263

Fix RxSwipeDismissBehavior flaky test

---

dependencies.gradle
rxbinding-support-v4/build.gradle

Because other artifacts might depend on older versions of support-v4, force them to the current version so that normal resolution semantics apply properly.
Closes #279.

Depend only on the Core UI artifact from support-v4.

---

buildSrc/src/main/kotlin/com/jakewharton/rxbinding/project/KotlinGenTask.kt
rxbinding-design-kotlin/src/main/kotlin/com/jakewharton/rxbinding/support/design/widget/RxTextInputLayout.kt
rxbinding-design/src/main/java/com/jakewharton/rxbinding/support/design/widget/RxTextInputLayout.java
rxbinding/src/main/java/com/jakewharton/rxbinding/internal/GenericTypeNullable.java

Introduces the `@GenericTypeNullable` annotation to mark nullable return type parameters. 
If this needs to be torn up, let me know, this is my first whack at it.
Fixes #297

generic type nullable

---

rxbinding-appcompat-v7/src/androidTest/java/com/jakewharton/rxbinding2/support/v7/widget/RxPopupMenuTest.java
rxbinding-appcompat-v7/src/androidTest/java/com/jakewharton/rxbinding2/support/v7/widget/RxToolbarTest.java

This assertions verify only is something was emitted. It started to fail since we returns `notification` instead of null.

FIx tests after converting Void to Object

---

rxbinding-appcompat-v7-kotlin/src/main/AndroidManifest.xml
rxbinding-design-kotlin/src/main/AndroidManifest.xml
rxbinding-kotlin/src/main/AndroidManifest.xml
rxbinding-leanback-v17-kotlin/src/main/AndroidManifest.xml
rxbinding-recyclerview-v7-kotlin/src/main/AndroidManifest.xml
rxbinding-support-v4-kotlin/src/main/AndroidManifest.xml
rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxSwipeRefreshLayoutTest.java
rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxSwipeRefreshLayoutTestActivity.java
rxbinding-support-v4/src/main/AndroidManifest.xml
rxbinding/src/androidTest/AndroidManifest.xml
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/view/RxMenuItemTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxAutoCompleteTextViewTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxAutoCompleteTextViewTestActivity.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxTextViewTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxToolbarTest.java
rxbinding/src/main/AndroidManifest.xml

I tried to use the old version and the new version together but the BuildConfig file conflicted. So I changed the package name of AndroidManifest.
```
compile "com.github.JakeWharton.RxBinding:rxbinding-kotlin:0.4.0"
compile "com.jakewharton.rxbinding:rxbinding-support-v4-kotlin:31e02dcaca"
```

Fix package in AndroidManifest for RxJava2

---

rxbinding-appcompat-v7-kotlin/build.gradle
rxbinding-design-kotlin/build.gradle
rxbinding-kotlin/build.gradle
rxbinding-leanback-v17-kotlin/build.gradle
rxbinding-recyclerview-v7-kotlin/build.gradle
rxbinding-support-v4-kotlin/build.gradle

The following problem occurred after #352. 😨 
Duplicating META-INF/rxbinding-kotlin-compileReleaseKotlin.kotlin_module files
```
Execution failed for task ':...transformResourcesWithMergeJavaResForProductRelease'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/rxbinding-kotlin-compileReleaseKotlin.kotlin_module
File1: .../build/intermediates/exploded-aar/com.jakewharton.rxbinding/rxbinding-kotlin/0.4.0/jars/classes.jar
File2: .../build/intermediates/exploded-aar/com.github.JakeWharton.RxBinding/rxbinding-kotlin/93b010afdc/jars/classes.jar
```
It worked if I used bellow options.
https://blog.jetbrains.com/kotlin/2015/09/kotlin-m13-is-out/
`New layout of .class files for top-level …

Avoid duplicating kotlin_module file

---

dependencies.gradle
rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Functions.java
rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/GenericTypeNullable.java
rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Notification.java
rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java
rxbinding/src/main/java/com/jakewharton/rxbinding2/view/RxView.java
rxbinding/src/main/java/com/jakewharton/rxbinding2/view/ViewEvent.java

Inline checkArgument method which was only used twice (and both inside a single method).

Restrict internal APIs to library group.

---

rxbinding-design/src/main/java/com/jakewharton/rxbinding2/support/design/widget/SnackbarDismissesObservable.java

setCallback is deprecated and should be replaced with the usage of addCallback and removeCallback. The PR applies the change.
the tests ran fine locally.

FIX: Use of Snackbar.add/removeCallback instead of setCallback.

---

rxbinding-appcompat-v7/src/androidTest/java/com/jakewharton/rxbinding2/support/v7/widget/RxPopupMenuTest.java
rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding2/support/v7/widget/SearchViewQueryTextChangeEventsObservable.java
rxbinding-design/src/main/java/com/jakewharton/rxbinding2/support/design/widget/SnackbarDismissesObservable.java
rxbinding-design/src/main/java/com/jakewharton/rxbinding2/support/design/widget/TabLayoutSelectionEventObservable.java
rxbinding-recyclerview-v7/src/androidTest/java/com/jakewharton/rxbinding2/support/v7/widget/RxRecyclerViewAdapterTest.java
rxbinding-recyclerview-v7/src/androidTest/java/com/jakewharton/rxbinding2/support/v7/widget/RxRecyclerViewTest.java
rxbinding-recyclerview-v7/src/main/java/com/jakewharton/rxbinding2/support/v7/widget/RecyclerAdapterDataChangeObservable.java
rxbinding-recyclerview-v7/src/main/java/com/jakewharton/rxbinding2/support/v7/widget/RecyclerViewScrollEventObservable.java
rxbinding-recyclerview-v7/src/main/java/com/jakewharton/rxbinding2/support/v7/widget/RecyclerViewScrollStateChangeObservable.java
rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/view/RxViewPagerTestActivity.java
rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxDrawerLayoutTest.java
rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxSlidingPaneLayoutTest.java
rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding2/support/v4/widget/RxSwipeRefreshLayoutTestActivity.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/view/RxViewAttachTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/view/RxViewSystemUiVisibilityTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxAbsListViewTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxAbsListViewTestActivity.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxAdapterTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxAdapterViewTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxAutoCompleteTextViewTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxPopupMenuTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxRatingBarTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/widget/RxSeekBarTest.java
rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/AdapterDataChangeObservable.java

Made package-private all private members accessed from inner classes, including tests.
fix #379 
the tests ran fine here: https://travis-ci.org/oldergod/RxBinding/builds/230737839

FIX: Private member access between outer and inner classes

---

rxbinding/src/androidTest/java/com/jakewharton/rxbinding2/internal/PreconditionsTest.java
rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java

Call onSubscribe before onError when main thread check fails.

---

rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding2/support/v4/view/ViewPagerPageScrollStateChangedObservable.java

Since onDispose is called exactly once there is no need to check is it was already disposed.
It fixes #406

Fix ViewPagerPageScrollStateChangedObservable

---

buildSrc/src/main/kotlin/com/jakewharton/rxbinding/project/conversion/MethodConverter.kt
buildSrc/src/main/kotlin/com/jakewharton/rxbinding/project/conversion/cleanedDocumentation.kt
rxbinding-appcompat-v7-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/support/v7/widget/RxToolbar.kt
rxbinding-appcompat-v7/src/main/java/com/jakewharton/rxbinding2/support/v7/widget/RxToolbar.java
rxbinding-design-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/support/design/widget/RxTextInputLayout.kt
rxbinding-design/src/main/java/com/jakewharton/rxbinding2/support/design/widget/RxTextInputLayout.java
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/view/RxMenuItem.kt
rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/view/RxView.kt
rxbinding-leanback-v17-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/support/v17/leanback/widget/RxSearchBar.kt
rxbinding-leanback-v17/src/main/java/com/jakewharton/rxbinding2/support/v17/leanback/widget/RxSearchBar.java
rxbinding-support-v4-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/support/v4/view/RxViewPager.kt
rxbinding-support-v4-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/support/v4/widget/RxSwipeRefreshLayout.kt
rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding2/support/v4/view/RxViewPager.java
rxbinding-support-v4/src/main/java/com/jakewharton/rxbinding2/support/v4/widget/RxSwipeRefreshLayout.java
rxbinding/src/main/java/com/jakewharton/rxbinding2/view/RxMenuItem.java
rxbinding/src/main/java/com/jakewharton/rxbinding2/view/RxView.java

Deprecate simple consumers in favor of method references.

---

rxbinding-appcompat-v7-kotlin/build.gradle
rxbinding-design-kotlin/build.gradle
rxbinding-kotlin/build.gradle
rxbinding-leanback-v17-kotlin/build.gradle
rxbinding-recyclerview-v7-kotlin/build.gradle
rxbinding-support-v4-kotlin/build.gradle

We expect them to only be consumed from Kotlin code.

Disable null parameter checks in Kotlin bindings.

---

rxbinding/src/main/java/com/jakewharton/rxbinding3/widget/AdapterViewItemClickEventObservable.kt
rxbinding/src/main/java/com/jakewharton/rxbinding3/widget/AdapterViewItemClickObservable.kt
rxbinding/src/main/java/com/jakewharton/rxbinding3/widget/AdapterViewItemLongClickEventObservable.kt
rxbinding/src/main/java/com/jakewharton/rxbinding3/widget/AdapterViewItemLongClickObservable.kt
rxbinding/src/main/java/com/jakewharton/rxbinding3/widget/AdapterViewItemSelectionObservable.kt
rxbinding/src/main/java/com/jakewharton/rxbinding3/widget/AdapterViewSelectionEvent.kt
rxbinding/src/main/java/com/jakewharton/rxbinding3/widget/AdapterViewSelectionObservable.kt
rxbinding/src/main/java/com/jakewharton/rxbinding3/widget/AutoCompleteTextViewItemClickEventObservable.kt

Not sure if I got all the places that this change is necessary in all of RxBindings, but at least this will fix the null pointer issue for `AdapterView` related events.
Fixes #485

Make View param nullable on AdapterView events

---

rxbinding-material/src/androidTest/java/com/jakewharton/rxbinding3/material/RxChipTest.kt
rxbinding-material/src/main/java/com/jakewharton/rxbinding3/material/ChipCloseIconClicksObservable.kt

As `Chip` inherits from `CompoundButton`, it already has `checkedChanges()` and `clicks()` bindings by default, so I've just added the remaining one as per [documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/Chip.md#handling-clicks)

Add Chip close icon clicks observable

---

build.gradle
rxbinding-appcompat/build.gradle
rxbinding-appcompat/src/androidTest/java/com/jakewharton/rxbinding3/appcompat/RxActionMenuViewTest.java
rxbinding-appcompat/src/androidTest/java/com/jakewharton/rxbinding3/appcompat/RxSearchViewTest.java
rxbinding-drawerlayout/src/androidTest/java/com/jakewharton/rxbinding3/drawerlayout/RxDrawerLayoutTest.java
rxbinding-leanback/build.gradle
rxbinding-leanback/src/androidTest/java/com/jakewharton/rxbinding3/leanback/RxSearchEditTextTest.java
rxbinding-material/build.gradle
rxbinding-material/src/androidTest/java/com/jakewharton/rxbinding3/material/RxAppBarLayoutTest.java
rxbinding-material/src/androidTest/java/com/jakewharton/rxbinding3/material/RxBottomNavigationViewTest.java
rxbinding-material/src/androidTest/java/com/jakewharton/rxbinding3/material/RxChipTest.kt
rxbinding-material/src/androidTest/java/com/jakewharton/rxbinding3/material/RxFloatingActionButtonTest.java
rxbinding-material/src/androidTest/java/com/jakewharton/rxbinding3/material/RxNavigationViewTest.java
rxbinding-material/src/androidTest/java/com/jakewharton/rxbinding3/material/RxSnackbarTest.java
rxbinding-material/src/androidTest/java/com/jakewharton/rxbinding3/material/RxTabLayoutTest.java
rxbinding-recyclerview/src/androidTest/java/com/jakewharton/rxbinding3/recyclerview/RxRecyclerViewTest.java
rxbinding-slidingpanelayout/src/androidTest/java/com/jakewharton/rxbinding3/slidingpanelayout/RxSlidingPaneLayoutTest.java
rxbinding/build.gradle
rxbinding/src/androidTest/java/com/jakewharton/rxbinding3/view/RxMenuItemTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding3/view/RxViewGroupTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding3/view/RxViewTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding3/widget/RxCompoundButtonTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding3/widget/RxRadioGroupTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding3/widget/RxSearchViewTest.java
rxbinding/src/androidTest/java/com/jakewharton/rxbinding3/widget/RxTextViewTest.java

`androidx.test.InstrumentationRegistry` is a deprecated class. This PR removes all the places where we were using it.

Fix InstrumentationRegistry deprecation

---

gradle/gradle-mvn-push.gradle

Publish sources to Maven Central
